import { MATERIAL_COLOR_ROLES } from './types.js';
import type {
  MaterialColorCssOptions,
  MaterialColorCssVariable,
  MaterialColorCssVariables,
  MaterialColorRole,
  MaterialColorScheme,
} from './types.js';

function roleToKebabCase(role: MaterialColorRole): string {
  return role.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);
}

export function materialColorRoleToCssVariable(
  role: MaterialColorRole,
): MaterialColorCssVariable {
  return `--md-sys-color-${roleToKebabCase(role)}`;
}

/** Converts generated semantic roles to Material-style CSS custom properties. */
export function toMaterialColorCssVariables(
  scheme: MaterialColorScheme,
): MaterialColorCssVariables {
  return Object.freeze(
    Object.fromEntries(
      MATERIAL_COLOR_ROLES.map((role) => [
        materialColorRoleToCssVariable(role),
        scheme.roles[role],
      ]),
    ),
  ) as MaterialColorCssVariables;
}

/** Serializes a generated scheme without reading or mutating the DOM. */
export function toMaterialColorCss(
  scheme: MaterialColorScheme,
  options: MaterialColorCssOptions = {},
): string {
  const selector = options.selector?.trim() ?? ':root';
  if (selector.length === 0) {
    throw new TypeError('selector must not be empty.');
  }

  const source = scheme.provenance;
  const declarations = MATERIAL_COLOR_ROLES.map((role) => {
    const variable = materialColorRoleToCssVariable(role);
    return `  ${variable}: ${scheme.roles[role]};`;
  }).join('\n');

  return [
    '/*',
    ` * Generated by ${source.packageName}@${source.packageVersion}`,
    ` * Source revision: ${source.sourceRevision}`,
    ` * Material color spec: ${source.materialSpecVersion}; model: ${source.materialPlatform}`,
    ` * Seed: ${source.seed}; variant: ${source.variant}; contrast: ${source.contrastLevel}; mode: ${source.mode}`,
    ' */',
    `${selector} {`,
    declarations,
    '}',
    '',
  ].join('\n');
}
